### ISSUE TITLE
Feature request: run one given ctest

### ISSUE THREAD

**Issue by tianyin** [xlab-uiuc/openctest#2]
The current run scripts can only run ALL ctests for a given parameter. 

@Alex-Lian Could you sent a PR for running one given ctest for a given parameter since you need that? 

@sampalomad @marshtompsxd Could you help review the PR later?

**Comment by thakkarparth007** [comment]
Fixed in #3

**Comment by tianyin** [comment]
Awesome! thanks @thakkarparth007 !!
