### ISSUE TITLE
About Maven

### ISSUE THREAD

**Issue by MEILIDEKCL** [xlab-uiuc/openctest#38]
When I try to build the hdfs project following the given scripts, but I don't get the right results. In ~/app/ctest-hadoop/hadoop-hdfs-project/hadoop-hdfs/target/classes directory, there is no core-ctest.xml which I have built in hadoop-common.
I have tried to find the reason, but nothing has been gained.I deteled the .m2 directory, but it doesn't work.
 So, do you have any suggestions for me? Thank you so much.

**Comment by xylian86** [comment]
@MEILIDEKCL Thanks for the questions. 

The potential solutions are:
1. Please check whether the hadoop is in the `ctest-injection` branch
2. The name of the file for injection for `hdfs` is `hdfs-ctest.xml` instead of `core-ctest.xml`.
3. And you need to build the hdfs module so that the `hdfs-ctest.xml` in `src` will be copied to `target`.

**Comment by MEILIDEKCL** [comment]
@Alex-Lian Thanks for your response.
1. I am surely in the `ctest-injection` branch
2. Yes, `hdfs` project need `hdfs-ctest.xml`. But I find that in your source code(`ctest_const.py`), the INJECTION_PATH for HDFS needs two xml (`core-ctest.xml` and `hdfs-ctest.xml`)
3. I followed the scripts `add_project.sh` ctest gived

**Comment by xylian86** [comment]
@MEILIDEKCL I think it is a bug in the `ctest_const.py`. For `hdfs`, we only need to inject value to `hdfs-ctest.xml` file. I need to double check with @marshtompsxd.

**Comment by MEILIDEKCL** [comment]
@Alex-Lian Thanks for your help.

**Comment by marshtompsxd** [comment]
We found some test cases in HDFS does not load `hdfs-xxx.xml` so we injected to both to make sure the injection takes effect. In most cases, injecting to `hdfs-ctest.xml` should be enough for HDFS.

**Comment by MEILIDEKCL** [comment]
@marshtompsxd Yeah, Thank you. But is there any questions for buliding the project on `HDFS`? I mean why `core-ctest.xml` wasn't  compiled into `target/class` directory? Thank you.

**Comment by xylian86** [comment]
@MEILIDEKCL For `Hcommon`, the filename for injection is `core-ctest.xml`. While for `HDFS`, the filename is `hdfs-ctest.xml`. 

And you can find the `hdfs-ctest.xml` file here. https://github.com/xlab-uiuc/hadoop/tree/ctest-injection/hadoop-hdfs-project/hadoop-hdfs/src/main/resources

**Comment by MEILIDEKCL** [comment]
Oh, yeah. Thank you.
